- name: Simple deployment with Ansible
  hosts: web
  become: true

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Create a CI/CD test file
      copy:
        dest: /tmp/deployed_by_ansible.txt
        content: "Deployed by Ansible via GitHub Actions at {{ ansible_date_time.iso8601 }}"
