# name: Ansible Deployment

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     name: Run Ansible Playbook
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.x'

#       - name: Install dependencies
#         run: |
#           pip install -r ansible/requirements.txt

#       - name: Write private key
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa

#       - name: Add host to known_hosts
#         run: |
#           ssh-keyscan -H ${{ secrets.TARGET_HOST }} >> ~/.ssh/known_hosts

#       - name: Replace host IP in inventory
#         run: |
#           sed -i "s|\${TARGET_HOST}|${{ secrets.TARGET_HOST }}|g" ansible/inventory.ini

#       - name: Run Ansible Playbook
#         run: |
#           ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --private-key ~/.ssh/id_rsa
