plugin: aws_ec2
regions:
  - eu-central-1
keyed_groups:
  - key: tags.Environment
    prefix: env
filters:
  instance-state-name: running
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address
